# Dependencies
markdown:             kramdown
highlighter:          rouge


# Gems
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-seo-tag


# Settings
color:                
  primary:            '#11DD88'
exclude:              [CNAME, README.md, NOTES.md, .gitignore, js, sass, .gulpfile, node_modules]
sass:
  sass_dir:           _sass
  style:              compressed


# Site meta
title:                Spring
tagline:              'A one-page, two-column Jekyll theme.'
keywords:             'connor, baer, bear, designer, developer, traveller, design, code, jekyll, wordpress, craft, cms, squarespace, for hire, spring'
description:          'A one-page, two-column Jekyll theme that pairs beautifully styled content with contextual media.'
url:                  http://spring.connorbaer.io
baseurl:              ''
logo:                 /assets/apple-icon-144x144.png
image:                spring
twitter:
  username:           connor_baer
facebook:
  app_id:             169140053203395

google_analytics_key: UA-37412525-4 
google_site_verification: Z-pc_HPc4XNBz8xg1fgtxO2MSIYLirZc2jWTNq0bJyM

author:
  name:               Connor Bär
  url:                http://connorbaer.io
  email:              hello@connorbaer.io
  twitter:            connor_baer

social:
  name:               Connor Bär
  links:              
    - https://twitter.com/connor_baer
    - https://instagram.com/connor_baer
    - https://github.com/connor-baer
    - https://medium.com/@connor_baer
    - https://www.snapchat.com/add/connor_baer

## Allows you to add external links to the navigation. Remove, add and re-arrange to your convenience.
nav_items:
  Medium:             https://medium.com/@connor_baer
  Twitter:            https://twitter.com/connor_baer
  Github:             https://github.com/connor-baer

version:              3.0.0

github:
  repo:               https://github.com/connor-baer/spring
